imbc_tankopedia:
    resource: "@ImbcTankopediaBundle/Resources/config/routing.yml"
    prefix:   /tankopedia

login:
    pattern:   /login
    defaults:  { _controller: ImbcSecurityBundle:Security:login }
    
login_check:
    pattern:   /login_check