<?php

namespace Imbc\TankopediaBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Engine
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EngineRepository extends EntityRepository
{
}
