<?php

namespace Imbc\TankopediaBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Nationality
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NationalityRepository extends EntityRepository
{
    public function getNationalities()
    {
        $data = array();
        $entities = $this->createQueryBuilder( 'n' )
                         ->orderBy( 'n.name', 'DESC' )
                         ->getQuery()->getResult();
         foreach( $entities as $e )
         {
             $data[$e->getAbreviation()] = $e->getName();
         }
         return $data;
    }
}
