<?php

namespace Imbc\TankopediaBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Type
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TankClassRepository extends EntityRepository
{
}
