<?php

namespace Imbc\TankopediaBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Tier
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TierRepository extends EntityRepository
{
    public function getTierByValue( $value )
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select( 't' );
        $qb->from( 'ImbcTankopediaBundle:Tier', 't' );
        $qb->add( 'where', $qb->expr()->eq( 't.value', ':value' ));
        $qb->setParameter( 'value', $value );

        return $qb->getQuery()->getSingleResult();
    }

}
