<?php

namespace Imbc\TankopediaBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Track
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Track extends EntityRepository
{
}
