tankopedia_nationality:
    pattern:  /
    defaults: { _controller: "ImbcTankopediaBundle:Nationality:index" }

tankopedia_nationality_show:
    pattern:  /{id}/show
    defaults: { _controller: "ImbcTankopediaBundle:Nationality:show" }

tankopedia_nationality_new:
    pattern:  /new
    defaults: { _controller: "ImbcTankopediaBundle:Nationality:new" }

tankopedia_nationality_create:
    pattern:  /create
    defaults: { _controller: "ImbcTankopediaBundle:Nationality:create" }
    requirements: { _method: post }

tankopedia_nationality_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ImbcTankopediaBundle:Nationality:edit" }

tankopedia_nationality_update:
    pattern:  /{id}/update
    defaults: { _controller: "ImbcTankopediaBundle:Nationality:update" }
    requirements: { _method: post|put }

tankopedia_nationality_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ImbcTankopediaBundle:Nationality:delete" }
    requirements: { _method: post|delete }
