tankopedia_nationality:
    pattern:  /
    defaults: { _controller: "ImbcTankopediaBundle:Nationality:index" }

tankopedia_nationality_show:
    pattern:  /{id}/show
    defaults: { _controller: "ImbcTankopediaBundle:Nationality:show" }

tankopedia_nationality_new:
    pattern:  /new
    defaults: { _controller: "ImbcTankopediaBundle:Nationality:edit" }

tankopedia_nationality_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ImbcTankopediaBundle:Nationality:edit" }

