tankopedia_radio:
    pattern:  /
    defaults: { _controller: "ImbcTankopediaBundle:Radio:index" }

tankopedia_radio_show:
    pattern:  /{id}/show
    defaults: { _controller: "ImbcTankopediaBundle:Radio:show" }

tankopedia_radio_new:
    pattern:  /new
    defaults: { _controller: "ImbcTankopediaBundle:Radio:edit" }

tankopedia_radio_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ImbcTankopediaBundle:Radio:edit" }