tankopedia_class:
    pattern:  /
    defaults: { _controller: "ImbcTankopediaBundle:TankClass:index" }

tankopedia_class_show:
    pattern:  /{slug}/show
    defaults: { _controller: "ImbcTankopediaBundle:TankClass:show" }

tankopedia_class_new:
    pattern:  /new
    defaults: { _controller: "ImbcTankopediaBundle:TankClass:edit" }

tankopedia_class_edit:
    pattern:  /{slug}/edit
    defaults: { _controller: "ImbcTankopediaBundle:TankClass:edit" }
