tankopedia_tier:
    pattern:  /
    defaults: { _controller: "ImbcTankopediaBundle:Tier:index" }

tankopedia_tier_show:
    pattern:  /{slug}/show
    defaults: { _controller: "ImbcTankopediaBundle:Tier:show" }

tankopedia_tier_new:
    pattern:  /new
    defaults: { _controller: "ImbcTankopediaBundle:Tier:edit" }

tankopedia_tier_edit:
    pattern:  /{slug}/edit
    defaults: { _controller: "ImbcTankopediaBundle:Tier:edit" }
