tankopedia_track:
    pattern:  /
    defaults: { _controller: "ImbcTankopediaBundle:Track:index" }

tankopedia_track_show:
    pattern:  /{slug}/show
    defaults: { _controller: "ImbcTankopediaBundle:Track:show" }

tankopedia_track_new:
    pattern:  /new
    defaults: { _controller: "ImbcTankopediaBundle:Track:edit" }

tankopedia_track_edit:
    pattern:  /{slug}/edit
    defaults: { _controller: "ImbcTankopediaBundle:Track:edit" }