tankopedia_turret:
    pattern:  /
    defaults: { _controller: "ImbcTankopediaBundle:Turret:index" }

tankopedia_turret_show:
    pattern:  /{slug}/show
    defaults: { _controller: "ImbcTankopediaBundle:Turret:show" }

tankopedia_turret_new:
    pattern:  /new
    defaults: { _controller: "ImbcTankopediaBundle:Turret:edit" }

tankopedia_turret_edit:
    pattern:  /{slug}/edit
    defaults: { _controller: "ImbcTankopediaBundle:Turret:edit" }